projects:
  imagescomments:
    schemaPath: amplify/backend/api/imagescomments/build/schema.graphql
    includes:
      - src/main/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/main/graphql
extensions:
  amplify:
    version: 3
